version: "3"
services:
  tree-demo-ui:
    image: crpi-yacuoj1e11qkasck.cn-beijing.personal.cr.aliyuncs.com/jiaozenghui/tree-demo-ui:{{tag}}
    container_name: tree-demo-ui
    networks:
      - blog_net
    ports:
      - 8899:80
networks:
  blog_net:
    name: mynet
    external: true
